/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpusView;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import sistemperpusController.*;
import sistemperpusModel.*;
/**
 *
 * @author Mira
 */
public class formPinjam extends javax.swing.JFrame {
    olahBukuController Bcontroller = new olahBukuController();
    olahAnggotaController Acontroller = new olahAnggotaController();
    searchController Scontroller = new searchController();
    peminjamanController controller = new peminjamanController();
    SimpleDateFormat dt = new SimpleDateFormat ("dd/MM/YYYY");
    static Buku Btemp;
    Peminjaman temp;
    List[] container = new ArrayList[2];
    List<Anggota> aRep = new ArrayList();
    List<Buku> bRep = new ArrayList();
    /**
     * Creates new form formPinjam
     * @param A
     */
    public formPinjam(Buku A) {
        initComponents();
        Btemp = A;
        temp = controller.initForm(Btemp);
        this.boxISBN.setText(temp.isbn);
        this.boxKembali.setText(dt.format(temp.tgl_kembali));
        this.boxPinjam.setText(dt.format(temp.tgl_pinjam));
        aRep = Acontroller.initData();
        bRep = Bcontroller.initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        labelNIPM = new javax.swing.JLabel();
        labelISBN = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        boxNIPM = new javax.swing.JTextField();
        boxISBN = new javax.swing.JTextField();
        boxPinjam = new javax.swing.JTextField();
        boxKembali = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMember = new javax.swing.JMenu();
        menuCari = new javax.swing.JMenuItem();
        menuKembali = new javax.swing.JMenuItem();
        menuDenda = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        menuDataAnggota = new javax.swing.JMenuItem();
        menuDataBuku = new javax.swing.JMenuItem();
        menuDataPinjam = new javax.swing.JMenuItem();
        menuDataKembali = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(737, 489));

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("e-Library Polban");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Form Peminjaman");

        labelNIPM.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelNIPM.setText("NIP/NIM");

        labelISBN.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        labelISBN.setText("ISBN");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Tgl. Pinjam");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Tgl. Kembali");

        boxISBN.setEditable(false);
        boxISBN.setText(" ");

        boxPinjam.setEditable(false);
        boxPinjam.setText(" ");

        boxKembali.setEditable(false);
        boxKembali.setText(" ");

        jButton1.setText("Pinjam");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        menuMember.setText("Anggota");

        menuCari.setText("Cari Buku");
        menuCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCariActionPerformed(evt);
            }
        });
        menuMember.add(menuCari);

        menuKembali.setText("Pengembalian");
        menuMember.add(menuKembali);

        menuDenda.setText("Bayar Denda");
        menuMember.add(menuDenda);

        jMenuBar1.add(menuMember);

        menuAdmin.setText("Admin");

        menuDataAnggota.setText("Data Anggota");
        menuDataAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataAnggotaActionPerformed(evt);
            }
        });
        menuAdmin.add(menuDataAnggota);

        menuDataBuku.setText("Data Buku");
        menuDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataBukuActionPerformed(evt);
            }
        });
        menuAdmin.add(menuDataBuku);

        menuDataPinjam.setText("Data Peminjaman");
        menuAdmin.add(menuDataPinjam);

        menuDataKembali.setText("Data Pengembalian");
        menuAdmin.add(menuDataKembali);

        jMenuBar1.add(menuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 698, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(title)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNIPM)
                            .addComponent(labelISBN)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(boxNIPM, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(labelNIPM))
                    .addComponent(boxNIPM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelISBN)
                    .addComponent(boxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(boxPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(boxKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(jButton1)
                .addGap(100, 100, 100))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCariActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Scontroller.startApplication();
        dispose();
    }//GEN-LAST:event_menuCariActionPerformed

    private void menuDataAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDataAnggotaActionPerformed

    private void menuDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataBukuActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Bcontroller.openBuku();
        dispose();
    }//GEN-LAST:event_menuDataBukuActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (boxNIPM.getText().equals(""))
            JOptionPane.showMessageDialog(null,"NIP/NIM tidak boleh kosong!");
        else {
            temp.nipm = boxNIPM.getText();
            controller.pinjam(temp, aRep, bRep);
            //aRep.clear(); bRep.clear();
            //aRep.addAll(container[0]);
            //bRep.addAll(container[1]);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formPinjam.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formPinjam(Btemp).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxISBN;
    private javax.swing.JTextField boxKembali;
    private javax.swing.JTextField boxNIPM;
    private javax.swing.JTextField boxPinjam;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelISBN;
    private javax.swing.JLabel labelNIPM;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuCari;
    private javax.swing.JMenuItem menuDataAnggota;
    private javax.swing.JMenuItem menuDataBuku;
    private javax.swing.JMenuItem menuDataKembali;
    private javax.swing.JMenuItem menuDataPinjam;
    private javax.swing.JMenuItem menuDenda;
    private javax.swing.JMenuItem menuKembali;
    private javax.swing.JMenu menuMember;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
