/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemperpusView;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import sistemperpusController.*;
import sistemperpusModel.*;

/**
 *
 * @author Mira
 */
public class olahBukuView extends javax.swing.JFrame {
    List<Buku> repBuku = new ArrayList();
    Buku temp;
    olahBukuController controller = new olahBukuController();
    DefaultTableModel model = new DefaultTableModel();
    /**
     * Creates new form olahBukuView
     */
    public olahBukuView() {
        repBuku = controller.initData();
        initComponents();
        this.resultTable.setModel(model);
        model.addColumn("ISBN");
        model.addColumn("Judul");
        model.addColumn("Pengarang");
        model.addColumn("Penerbit");
        model.addColumn("Sinopsis");
        model.addColumn("No.Rak");
        model.addColumn("Stok");
        ShowResult(repBuku);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelReadDelete = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        resultTable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panelAdd = new javax.swing.JPanel();
        label_isbn = new javax.swing.JLabel();
        label_judul = new javax.swing.JLabel();
        label_penerbit = new javax.swing.JLabel();
        label_author = new javax.swing.JLabel();
        label_sinopsis = new javax.swing.JLabel();
        label_norak = new javax.swing.JLabel();
        label_stok = new javax.swing.JLabel();
        boxISBN = new javax.swing.JTextField();
        boxJudul = new javax.swing.JTextField();
        boxAuthor = new javax.swing.JTextField();
        boxPenerbit = new javax.swing.JTextField();
        boxNorak = new javax.swing.JTextField();
        boxStok = new javax.swing.JSpinner();
        submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        boxSinopsis = new javax.swing.JTextPane();
        panelUpdate = new javax.swing.JPanel();
        label_isbn1 = new javax.swing.JLabel();
        label_judul1 = new javax.swing.JLabel();
        boxJudul1 = new javax.swing.JTextField();
        label_author1 = new javax.swing.JLabel();
        boxAuthor1 = new javax.swing.JTextField();
        label_penerbit1 = new javax.swing.JLabel();
        boxPenerbit1 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        boxSinopsis1 = new javax.swing.JTextPane();
        label_sinopsis1 = new javax.swing.JLabel();
        label_norak1 = new javax.swing.JLabel();
        boxNorak1 = new javax.swing.JTextField();
        boxStok1 = new javax.swing.JSpinner();
        label_stok1 = new javax.swing.JLabel();
        submit1 = new javax.swing.JButton();
        comboISBN = new javax.swing.JComboBox();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuMember = new javax.swing.JMenu();
        menuCari = new javax.swing.JMenuItem();
        menuKembali = new javax.swing.JMenuItem();
        menuDenda = new javax.swing.JMenuItem();
        menuAdmin = new javax.swing.JMenu();
        menuDataAnggota = new javax.swing.JMenuItem();
        menuDataBuku = new javax.swing.JMenuItem();
        menuDataPinjam = new javax.swing.JMenuItem();
        menuDataKembali = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        title.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        title.setText("e-Library Polban");

        resultTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resultTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(resultTable);

        jButton1.setText("Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelReadDeleteLayout = new javax.swing.GroupLayout(panelReadDelete);
        panelReadDelete.setLayout(panelReadDeleteLayout);
        panelReadDeleteLayout.setHorizontalGroup(
            panelReadDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelReadDeleteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        panelReadDeleteLayout.setVerticalGroup(
            panelReadDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelReadDeleteLayout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 307, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(panelReadDeleteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Data Buku", panelReadDelete);

        label_isbn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_isbn.setText("ISBN");

        label_judul.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_judul.setText("Judul Buku");

        label_penerbit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_penerbit.setText("Penerbit");

        label_author.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_author.setText("Pengarang");

        label_sinopsis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_sinopsis.setText("Sinopsis");

        label_norak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_norak.setText("No. Rak");

        label_stok.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_stok.setText("Stok");

        boxISBN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxISBNActionPerformed(evt);
            }
        });

        boxStok.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(boxSinopsis);

        javax.swing.GroupLayout panelAddLayout = new javax.swing.GroupLayout(panelAdd);
        panelAdd.setLayout(panelAddLayout);
        panelAddLayout.setHorizontalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_isbn)
                        .addComponent(label_judul)
                        .addComponent(label_stok)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_penerbit)
                            .addComponent(label_author)))
                    .addComponent(label_sinopsis)
                    .addComponent(label_norak))
                .addGap(44, 44, 44)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxNorak, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStok, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit)
                .addGap(35, 35, 35))
        );
        panelAddLayout.setVerticalGroup(
            panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_isbn)
                    .addComponent(boxISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxJudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_judul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxAuthor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_author))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxPenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_penerbit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_sinopsis)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNorak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_norak))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelAddLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_stok)
                    .addComponent(boxStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Tambah Buku", panelAdd);

        label_isbn1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_isbn1.setText("ISBN");

        label_judul1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_judul1.setText("Judul Buku");

        label_author1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_author1.setText("Pengarang");

        label_penerbit1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_penerbit1.setText("Penerbit");

        jScrollPane2.setViewportView(boxSinopsis1);

        label_sinopsis1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_sinopsis1.setText("Sinopsis");

        label_norak1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_norak1.setText("No. Rak");

        label_stok1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        label_stok1.setText("Stok");

        submit1.setText("Submit");

        comboISBN.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelUpdateLayout = new javax.swing.GroupLayout(panelUpdate);
        panelUpdate.setLayout(panelUpdateLayout);
        panelUpdateLayout.setHorizontalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(label_isbn1)
                        .addComponent(label_judul1)
                        .addComponent(label_stok1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label_penerbit1)
                            .addComponent(label_author1)))
                    .addComponent(label_sinopsis1)
                    .addComponent(label_norak1))
                .addGap(44, 44, 44)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxNorak1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxPenerbit1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxStok1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(comboISBN, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(boxJudul1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addContainerGap(176, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelUpdateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submit1)
                .addGap(35, 35, 35))
        );
        panelUpdateLayout.setVerticalGroup(
            panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelUpdateLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_isbn1)
                    .addComponent(comboISBN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxJudul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_judul1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxAuthor1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_author1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxPenerbit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_penerbit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_sinopsis1)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxNorak1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_norak1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_stok1)
                    .addComponent(boxStok1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Update Buku", panelUpdate);

        menuMember.setText("Anggota");

        menuCari.setText("Cari Buku");
        menuMember.add(menuCari);

        menuKembali.setText("Pengembalian");
        menuMember.add(menuKembali);

        menuDenda.setText("Bayar Denda");
        menuMember.add(menuDenda);

        jMenuBar1.add(menuMember);

        menuAdmin.setText("Admin");

        menuDataAnggota.setText("Data Anggota");
        menuDataAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataAnggotaActionPerformed(evt);
            }
        });
        menuAdmin.add(menuDataAnggota);

        menuDataBuku.setText("Data Buku");
        menuDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuDataBukuActionPerformed(evt);
            }
        });
        menuAdmin.add(menuDataBuku);

        menuDataPinjam.setText("Data Peminjaman");
        menuAdmin.add(menuDataPinjam);

        menuDataKembali.setText("Data Pengembalian");
        menuAdmin.add(menuDataKembali);

        jMenuBar1.add(menuAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boxISBNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxISBNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxISBNActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        controller.addBuku(boxISBN.getText(), boxJudul.getText(), boxPenerbit.getText(), 
                boxAuthor.getText(), boxSinopsis.getText(), boxNorak.getText(), (int) boxStok.getValue(), repBuku);
        this.jTabbedPane1.setSelectedIndex(0);
        ShowResult(repBuku);
    }//GEN-LAST:event_submitActionPerformed

    private void menuDataAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataAnggotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuDataAnggotaActionPerformed

    private void menuDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuDataBukuActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_menuDataBukuActionPerformed

    private void resultTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultTableMouseClicked
        // TODO add your handling code here:
        getRowValue();
    }//GEN-LAST:event_resultTableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            // TODO add your handling code here:
        repBuku  = controller.deleteBuku(temp.getISBN(), repBuku);
        ShowResult(repBuku);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        repBuku = controller.updateBuku(temp, repBuku);
        ShowResult(repBuku);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(olahBukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(olahBukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(olahBukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(olahBukuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new olahBukuView().setVisible(true);
            }
        });
    }
    
    private void ShowResult(List<Buku> resultList){
    
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        for(Object o : resultList){
            Buku temp = (Buku)o;
            Object[] oneRow = new Object[7];
            oneRow[0] = (temp.getISBN());
            oneRow[1] = (temp.getJudul());
            oneRow[2] = (temp.getAuthor());
            oneRow[3] = (temp.getPenerbit());
            oneRow[4] = (temp.getSinopsis());
            oneRow[5] = (temp.getnoRak());
            oneRow[6] = (temp.getStok());
            
            model.addRow(oneRow);
        }
    }
    
    private void getRowValue (){
        int i = this.resultTable.getSelectedRow();
        
        if (i == -1)
            return;
       
        String ISBN = (String)model.getValueAt(i, 0);
        String Judul = (String)model.getValueAt(i, 1);
        String Author = (String)model.getValueAt(i, 2);
        String Penerbit = (String)model.getValueAt(i, 3);
        String Sinopsis = (String)model.getValueAt(i, 4);
        String noRak = (String)model.getValueAt(i, 5);
        int stok = (int)model.getValueAt(i, 6);
        temp = new Buku (ISBN, Judul, Author, Penerbit, Sinopsis, noRak, stok);
        System.out.println(ISBN+Judul);    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField boxAuthor;
    private javax.swing.JTextField boxAuthor1;
    private javax.swing.JTextField boxISBN;
    private javax.swing.JTextField boxJudul;
    private javax.swing.JTextField boxJudul1;
    private javax.swing.JTextField boxNorak;
    private javax.swing.JTextField boxNorak1;
    private javax.swing.JTextField boxPenerbit;
    private javax.swing.JTextField boxPenerbit1;
    private javax.swing.JTextPane boxSinopsis;
    private javax.swing.JTextPane boxSinopsis1;
    private javax.swing.JSpinner boxStok;
    private javax.swing.JSpinner boxStok1;
    private javax.swing.JComboBox comboISBN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel label_author;
    private javax.swing.JLabel label_author1;
    private javax.swing.JLabel label_isbn;
    private javax.swing.JLabel label_isbn1;
    private javax.swing.JLabel label_judul;
    private javax.swing.JLabel label_judul1;
    private javax.swing.JLabel label_norak;
    private javax.swing.JLabel label_norak1;
    private javax.swing.JLabel label_penerbit;
    private javax.swing.JLabel label_penerbit1;
    private javax.swing.JLabel label_sinopsis;
    private javax.swing.JLabel label_sinopsis1;
    private javax.swing.JLabel label_stok;
    private javax.swing.JLabel label_stok1;
    private javax.swing.JMenu menuAdmin;
    private javax.swing.JMenuItem menuCari;
    private javax.swing.JMenuItem menuDataAnggota;
    private javax.swing.JMenuItem menuDataBuku;
    private javax.swing.JMenuItem menuDataKembali;
    private javax.swing.JMenuItem menuDataPinjam;
    private javax.swing.JMenuItem menuDenda;
    private javax.swing.JMenuItem menuKembali;
    private javax.swing.JMenu menuMember;
    private javax.swing.JPanel panelAdd;
    private javax.swing.JPanel panelReadDelete;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JTable resultTable;
    private javax.swing.JButton submit;
    private javax.swing.JButton submit1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
